name: Auto Update Profile Projects

on:
  schedule:
    - cron: "0 1 * * *"   # daily at 01:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Autoâ€‘update Projects
      uses: theboi/github-update-readme@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        readme-file: README.md
        sections: |
          projects: |
            type: pinned
            username: Malcom-Yingwani
            max-repos: 6
